# Generated by Django 3.0.8 on 2020-07-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='user',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
